### PR TITLE
Added speed related attributes to robotclass

### PR DESCRIPTION
**Pull request by DerApplaudeur**
Added the 6 attributes to the robot as described in Sprint 3.

For now the __init__: function hasn't changed since acceleration and speed should always start at 0.
We might want to add the maximums of speed and acceleration to the __init__ function since that would allow different robots to have differen max speeds/ accelerations but for quick testing this might be better for now.

In order to change all the new attributes that aren't maximums i added change_X functions for them.

### CODE REVIEW

**Comment by DerApplaudeur** [comment]
Nice that we have no more flake8 errors with the updated workflow :)

I updated the branch for easier testing, it is now mostly up to date with the current main branch.
I made multiple changes to both the robot and the movement class, aswell as to game.py in order for this new movement to work.

Current issues: 
- We have a maximum acceleration but no max velocity which mean that we can reach "light speed" which we probaly don't want to.
- the orientation changes with rotational acceleration are not jet implemented
- velocity has currently no effect on vertical velocity ie jumping and falling, only horizontal movement has been changed
- the current numbers are all placeholders to demonstate this working somewhat and are most definetly not balanced

**Comment by DerApplaudeur** [comment]
I added a for now constant speed limit, this is intended to limit the players "natural" movement to a certain speed.
For this i added a change_velocity_cap function, while keping  the previously used change_velocity function for case where we might want to ignore any limit.
This more or less "fixed" some unwanted movement quirks which appeared at quite high speed.

**Comment by DerApplaudeur** [comment]
I think this code is now passable but some feedback would be great as some changes might be needed for other planed features.

**Review by ManuShift — APPROVED** [review]
looks good and all the requirements from the brief have been met

**Pull request merged**
