### PR TITLE
added bouncy projectile

### PR DESCRIPTION
**Pull request by DerApplaudeur**
Completely ignoring everything we learned in SE i made all changes in one single commit.

New bouncy projectiles for now bound to the z key, they will bounce twice before deissapearing like all other projectiles, however we don't bounce off robots although that can be changed easily.

### CODE REVIEW

**Review by Luceleven — CHANGES_REQUESTED** [review]
Works in Single Player, but stops working in multiplayer.
And I wouldn't let them bounce of the map edges because these edges should be "open", but thats a design choice.
Also found another bug: If I shoot and I go back to the main menu while the projectile still flies and I start another round, the projectile resumes flying.

**Comment by DerApplaudeur** [comment]
The reason why the bounce was not working in multiplayer was because each bullet bounced once per player.
The bullets bouncing of the arena was something i did for testing but somehow forgott to remove.
And finally the projectiles not dissapearing appears to have been an old issue that we have just overlooked for a while.
All issues should be fixed now

**Review by Luceleven — APPROVED** [review]
All issues have been fixed.

**Comment by DerApplaudeur** [comment]
I merged main into this branch first in oder to update it easier and make sure i don't break anything while doing so.
Coincidentally i found out that the commit #[e24ae1e](https://github.com/RoboArenaDrolf/RoboArenaDroelf.github.io/pull/47/commits/e24ae1e6b9254b173ca7ce0160955ef62f429075),
broke all hit_reg for projectiles.
I found out that this happend because in the reset_projectiles function i simply used self.projectiles = [] which i have now replacred with a for loop that removes all items of the array instead.

**Pull request merged**
