### PR TITLE
Added basic Ranged attack

### PR DESCRIPTION
**Pull request by DerApplaudeur**
General Changes:
Changed the orientation of the robot to be limited to the 4 directions, up down left and right
The robot will face in the direction of the last direction key pressed
Jump was rebound to space to accomidate this

Ranged attack:
-moves at the maximum speed of robots
-already has collision with robots, however not with the terrain
Issues
bug: it's still somehow possible to hit yourself with these projectiles - should be fixed
current implementation is quite bad for performance - somewhat improved still not great

### CODE REVIEW

**Comment by DerApplaudeur** [comment]
Issue with cooldown inside the robot class:
Due to the fact that the robot class has no information about the current framecount this is difficult.
A iteration inside the robot class will increase an enormous amount of times within a single frame and will propably be inconsitend aswell.

For now the cooldown calculation must remain in the game loop until we find a way arround this.

**Comment by DerApplaudeur** [comment]
Update:
We have to iterate in the game loop to get the correct frame count for the attacks, but we can save the attack-durations and attack-cooldown elsewehere.
Still we wont be able to completely move the cooldown calculation outside of the main loop, or at least I don't know how.

**Comment by DerApplaudeur** [comment]
Now all Projectiles will disappear if they hit the walls of the arena, any Tile or any Robot.
I used a trimmed down version of the collision checks for robots for this purpose and we might be able to refactor both of these collision checks into a collision class later.

**Review by ManuShift — APPROVED** [review]
Everything works

**Pull request merged**
